version: "3.7"

services:
  server:
    container_name: x3dspotify
    image: x3dspotify:production
    env_file:
      - ./server/.env.production
    environment:
      - NODE_ENV=production
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - 8080:8080
