version: "3.7"

services:
  webclient:
    container_name: x3dspotify_webclient
    image: x3dsoptify:webclient
    build:
      context: ./webclient
      dockerfile: Dockerfile
    volumes:
      - "./webclient:/app"
      - "/app/node_modules"
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
  server:
    container_name: x3dspotify_server
    image: x3dapotify:server
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env.development
    volumes:
      - "./server:/app"
      - "/app/node_modules"
    ports:
      - 8080:8080
      - 12345:12345
